---
- hosts: primary
  name: Populate pgbench database
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Create pgbench user
      community.postgresql.postgresql_user:
        login_user: "{{ pg_owner }}"
        name: "{{ pgbench_user }}"
        password: "{{ pgbench_password }}"
        login_unix_socket: "{{ pg_unix_socket_directory }}"
        port: "{{ pg_port }}"
        login_db: postgres
        role_attr_flags: SUPERUSER
      become_user: "{{ pg_owner }}"

    - name: Create pgbench database
      community.postgresql.postgresql_db:
        login_user: "{{ pg_owner }}"
        name: "{{ pgbench_database }}"
        login_unix_socket: "{{ pg_unix_socket_directory }}"
        port: "{{ pg_port }}"
        encoding: UTF-8
        maintenance_db: postgres
        owner: "{{ pgbench_user }}"
      become_user: "{{ pg_owner }}"

    - name: Update pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/edb/as{{ pg_version }}/main/data/pg_hba.conf"
        contype: local
        users: "{{ pgbench_user }}"
        databases: "{{ pgbench_database }}"
        method: scram-sha-256
      become: true

    - name: Update pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/edb/as{{ pg_version }}/main/data/pg_hba.conf"
        contype: host
        users: "{{ pgbench_user }}"
        databases: "{{ pgbench_database }}"
        source: "0.0.0.0/0"
        method: scram-sha-256
      become: true

    - name: Update pg_hba.conf
      community.postgresql.postgresql_pg_hba:
        dest: "/var/lib/edb/as{{ pg_version }}/main/data/pg_hba.conf"
        contype: hostssl
        users: "{{ pgbench_user }}"
        databases: "{{ pgbench_database }}"
        source: "0.0.0.0/0"
        method: scram-sha-256
      become: true

    - name: Reload EPAS
      ansible.builtin.systemd:
        name: edb-as-14
        state: reloaded
      become: true

    - name: Populate pgbench database
      ansible.builtin.command:
        cmd: /usr/edb/as{{ pg_version }}/bin/pgbench -U {{ pgbench_user }} -h {{ pg_unix_socket_directory }} -i --partitions=100 -s {{ pgbench_scale_factor }} {{ pgbench_database }}
      environment:
        PGPASSWORD: "{{ pgbench_password }}"
      become_user: "{{ pg_owner }}"
      async: 180000
      poll: 60
