---
- hosts: all
  name: Setup replication and HA
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  roles:
    - role: setup_replication
      when: "'setup_replication' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_efm
      when: "'setup_efm' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
