---
- hosts: proxy
  name: Setup the proxy node
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: haproxy
        state: latest
      become: true

    - name: Configure haproxy
      ansible.builtin.template:
        dest: /etc/haproxy/haproxy.cfg
        src: files/haproxy.cfg.j2
        mode: 0644
      become: true

    - name: Enable HAProxy to bind to any IP
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes
      become: true

    - name: Start haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: yes
      become: true

    - name: Open TCP port 5444
      ansible.builtin.firewalld:
        port: "{{ pg_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      become: true
      ignore_errors: true
