---
- hosts: primary,standby
  name: Add network latency between EPAS nodes
  become: yes
  gather_facts: yes

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Install tc
      ansible.builtin.package:
        name: tc
        state: present
      become: true
      ignore_errors: true

    - name: Set ip_address
      ansible.builtin.set_fact:
        ip_address: "{{ hostvars[inventory_hostname].private_ip }}"

    - name: Populate ip_addresses with primary addr
      ansible.builtin.set_fact:
        ip_addresses: "{{ ip_addresses | default([]) + [ hostvars[item].private_ip ] }}"
      loop: "{{ groups['primary'] }}"
      when: hostvars[item].private_ip != ip_address

    - name: Populate ip_addresses with standby addrs
      ansible.builtin.set_fact:
        ip_addresses: "{{ ip_addresses | default([]) + [ hostvars[item].private_ip ] }}"
      loop: "{{ groups['standby'] }}"
      when: hostvars[item].private_ip != ip_address

    - name: debug
      ansible.builtin.debug:
        msg: "{{ ip_addresses }}"

    - name: Apply tc rules
      ansible.builtin.shell: |
        tc qdisc del dev {{ network_device }} root
        tc qdisc add dev {{ network_device }} root handle 1: prio
        tc qdisc add dev {{ network_device }} parent 1:3 handle 30: netem latency {{ pg_additional_network_latency }}
        {% for i in ip_addresses -%}
        tc filter add dev {{ network_device }} protocol ip parent 1:0 prio 3 u32 \
          match ip dst {{ i }} flowid 1:3
        {% endfor -%}
      become: true
