---
- hosts: primary
  name: Populate DBT2 database
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Populate DBT2 database
      ansible.builtin.command:
        cmd: dbt2-pgsql-build-db -l {{ pg_port }} -w {{ dbt2_warehouse }}
      environment:
        DBT2DBNAME: "dbt2"
        PATH: "/usr/pgsql-{{ pg_version }}/bin:{{ ansible_env.PATH }}"
      become_user: "{{ pg_owner }}"
      async: 180000
      poll: 60
      changed_when: false
      register: result

    - name: Database build output
      ansible.builtin.debug:
        var: result
