---
- hosts: primary
  name: Start system and database statisticss collection

  tasks:
    - name: Build TPROC-C database
      ansible.builtin.shell:
        cmd: ./hammerdbcli tcl auto /home/hammerdb/build.tcl
      args:
        chdir: "/home/hammerdb/HammerDB-{{ hammerdb_version }}"
      become: true
      become_user: "{{ hammerdb_user }}"
      register: result

    - name: Database build output
      ansible.builtin.debug:
        var: result
