---
- hosts: all
  name: Install repository
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: true

  roles:
    - role: setup_repo

- hosts: hammerdb_driver
  name: Install HammerDB
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - setup_hammerdb
    - setup_touchstone_tools

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Configure run.tcl
      ansible.builtin.template:
        dest: /home/{{ hammerdb_user }}/run.tcl
        src: templates/run.tcl.j2
        mode: '0755'
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"

- hosts: primary
  name: Setup EPAS
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        disable_logging: false
        pg_hba_ip_addresses:
          - contype: "host"
            users: "all"
            databases: "all"
            method: "trust"
            source: "10.0.0.0/24"
            state: present

        pg_shared_libraries_list:
          - "$libdir/dbms_pipe"
          - "$libdir/edb_gen"
          - "$libdir/dbms_aq"
          - "$libdir/edb_wait_states"
          - "$libdir/sql-profiler"
          - "$libdir/index_advisor"
          - "$libdir/pg_stat_statements"
          - "$libdir/auto_explain"

        pg_postgres_conf_params:
          - name: log_filename
            value: "postgresql.log"
          - name: default_with_rowids
            value: "on"
          - name: log_line_prefix
            value: "%t [%p]: user=%u,db=%d,app=%a,client=%h "
          - name: log_checkpoints
            value: "on"
          - name: log_connections
            value: "on"
          - name: log_disconnections
            value: "on"
          - name: log_lock_waits
            value: "on"
          - name: log_temp_files
            value: "0"
          - name: log_autovacuum_min_duration
            value: "0"
          - name: log_error_verbosity
            value: "default"
          - name: auto_explain.log_min_duration
            value: "0"
          - name: auto_explain.log_analyze
            value: "on"
          - name: auto_explain.log_wal
            value: "on"
          - name: auto_explain.log_timing
            value: "on"

  roles:
    - install_dbserver
    - init_dbserver
    - manage_dbserver
    - setup_hammerdb
    - setup_touchstone_tools

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Configure build.tcl
      ansible.builtin.template:
        dest: /home/{{ hammerdb_user }}/build.tcl
        src: templates/build.tcl.j2
        mode: '0755'
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"

- hosts: all
  name: Patch HammerDB
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Install patch
      ansible.builtin.package:
        name: patch

    - name: Copy patches to host
      ansible.builtin.copy:
        src: 0001-Match-postgresql-stored-procedures-to-oracle.patch
        dest: "/home/{{ hammerdb_user }}/\
              0001-Match-postgresql-stored-procedures-to-oracle.patch"
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"
        mode: '0644'
      become: true

    - name: Apply HammerDB patches
      ansible.posix.patch:
        src: 0001-Match-postgresql-stored-procedures-to-oracle.patch
        basedir: "/home/{{ hammerdb_user }}/HammerDB-{{ hammerdb_version }}"
        strip: 1
      become_user: "hammerdb"
